const vehicles = {
    "status": true,
    "message": "Success",
    "data": [
        {
            "vehicle_id": 688,
            "vehicle_category": "Sedan",
            "make": "Mitsubishi",
            "model": "Mitsubishi Attrage or Similar (CRX)",
            "vehicle_image": "https://ezhire.life/erp/media/2024/10/28/6066a94f-4bb.png",
            "daily_rate": 124.98,
            "weekly_rate": 124.76,
            "monthly_rate": 88.29,
            "tax_rate": 5,
            "currency": "AED",
            "total_estimated_amount_weekly": 131.0,
            "total_estimated_amount_daily": 131.23,
            "total_estimated_amount_monthly": 92.7,
            "daily_allowed_km": 225.0,
            "weekly_allowed_km": 200.0,
            "monthly_allowed_km": 133.33,
            "extra_km_price": 0.5,
            "transmission": "AT",
            "number_of_seats": 5,
            "air_conditioning": 1,
            "number_of_doors": 4,
            "luggage_capacity": 2,
            "car_name": "Mitsubishi Attrage or Similar (CRX)"
        },
        {
            "vehicle_id": 689,
            "vehicle_category": "Sedan",
            "make": "Nissan",
            "model": "Nissan Sunny or Simiaae (CRX)",
            "vehicle_image": "https://ezhire.life/erp/media/2024/10/28/0f841a3c-44a.jpg",
            "daily_rate": 124.98,
            "weekly_rate": 23.44,
            "monthly_rate": 93.69,
            "tax_rate": 5,
            "currency": "AED",
            "total_estimated_amount_weekly": 24.61,
            "total_estimated_amount_daily": 131.23,
            "total_estimated_amount_monthly": 98.37,
            "daily_allowed_km": 225.0,
            "weekly_allowed_km": 200.0,
            "monthly_allowed_km": 133.33,
            "extra_km_price": 0.5,
            "transmission": "AT",
            "number_of_seats": 5,
            "air_conditioning": 1,
            "number_of_doors": 4,
            "luggage_capacity": 2,
            "car_name": "Nissan Sunny or Simiaae (CRX)"
        },
        {
            "vehicle_id": 690,
            "vehicle_category": "HatchBack",
            "make": "Kia",
            "model": "Kia Picanto or Similar (CRX)",
            "vehicle_image": "https://ezhire.life/erp/media/2024/10/28/1f61c419-0b6.png",
            "daily_rate": 137.49,
            "weekly_rate": 130.18,
            "monthly_rate": 98.7,
            "tax_rate": 5,
            "currency": "AED",
            "total_estimated_amount_weekly": 136.69,
            "total_estimated_amount_daily": 144.36,
            "total_estimated_amount_monthly": 103.64,
            "daily_allowed_km": 225.0,
            "weekly_allowed_km": 200.0,
            "monthly_allowed_km": 133.33,
            "extra_km_price": 0.5,
            "transmission": "AT",
            "number_of_seats": 5,
            "air_conditioning": 1,
            "number_of_doors": 4,
            "luggage_capacity": 1,
            "car_name": "Kia Picanto or Similar (CRX)"
        },
        {
            "vehicle_id": 691,
            "vehicle_category": "Sedan",
            "make": "Toyota",
            "model": "Toyota Yaris Or Similar (CRX)",
            "vehicle_image": "https://ezhire.life/erp/media/2024/10/28/af446347-c54.png",
            "daily_rate": 140.6,
            "weekly_rate": 140.39,
            "monthly_rate": 105.15,
            "tax_rate": 5,
            "currency": "AED",
            "total_estimated_amount_weekly": 147.41,
            "total_estimated_amount_daily": 147.63,
            "total_estimated_amount_monthly": 110.41,
            "daily_allowed_km": 225.0,
            "weekly_allowed_km": 200.0,
            "monthly_allowed_km": 133.33,
            "extra_km_price": 0.5,
            "transmission": "AT",
            "number_of_seats": 5,
            "air_conditioning": 1,
            "number_of_doors": 4,
            "luggage_capacity": 2,
            "car_name": "Toyota Yaris Or Similar (CRX)"
        },
        {
            "vehicle_id": 692,
            "vehicle_category": "Sedan",
            "make": "Mazda",
            "model": "Mazda 6 Or Similar (CRX)",
            "vehicle_image": "https://ezhire.life/erp/media/2024/10/28/b858524e-780.png",
            "daily_rate": 249.98,
            "weekly_rate": 236.38,
            "monthly_rate": 124.41,
            "tax_rate": 5,
            "currency": "AED",
            "total_estimated_amount_weekly": 248.2,
            "total_estimated_amount_daily": 262.48,
            "total_estimated_amount_monthly": 130.63,
            "daily_allowed_km": 225.0,
            "weekly_allowed_km": 200.0,
            "monthly_allowed_km": 133.33,
            "extra_km_price": 0.8,
            "transmission": "AT",
            "number_of_seats": 5,
            "air_conditioning": 1,
            "number_of_doors": 4,
            "luggage_capacity": 2,
            "car_name": "Mazda 6 Or Similar (CRX)"
        },
        {
            "vehicle_id": 693,
            "vehicle_category": "SUV",
            "make": "Nissan",
            "model": "NIssan Kicks Or Similar (CRX)",
            "vehicle_image": "https://ezhire.life/erp/media/2024/10/28/a27f2ff6-7d9.jpg",
            "daily_rate": 249.98,
            "weekly_rate": 236.38,
            "monthly_rate": 122.34,
            "tax_rate": 5,
            "currency": "AED",
            "total_estimated_amount_weekly": 248.2,
            "total_estimated_amount_daily": 262.48,
            "total_estimated_amount_monthly": 128.46,
            "daily_allowed_km": 225.0,
            "weekly_allowed_km": 200.0,
            "monthly_allowed_km": 133.33,
            "extra_km_price": 0.8,
            "transmission": "AT",
            "number_of_seats": 5,
            "air_conditioning": 1,
            "number_of_doors": 5,
            "luggage_capacity": 4,
            "car_name": "NIssan Kicks Or Similar (CRX)"
        },
        {
            "vehicle_id": 694,
            "vehicle_category": "Sedan",
            "make": "Suzuki",
            "model": "Suzuki Ciaz Or Similar (CRX)",
            "vehicle_image": "https://ezhire.life/erp/media/2024/10/28/768fd776-03e.png",
            "daily_rate": 140.6,
            "weekly_rate": 140.39,
            "monthly_rate": 98.7,
            "tax_rate": 5,
            "currency": "AED",
            "total_estimated_amount_weekly": 147.41,
            "total_estimated_amount_daily": 147.63,
            "total_estimated_amount_monthly": 103.64,
            "daily_allowed_km": 0.0,
            "weekly_allowed_km": 0.0,
            "monthly_allowed_km": 0.0,
            "extra_km_price": 0.0,
            "transmission": "AT",
            "number_of_seats": 5,
            "air_conditioning": 1,
            "number_of_doors": 4,
            "luggage_capacity": 2,
            "car_name": "Suzuki Ciaz Or Similar (CRX)"
        },
        {
            "vehicle_id": 695,
            "vehicle_category": "SUV",
            "make": "Toyota",
            "model": "Toyota Fortuner & Similar (CRX)",
            "vehicle_image": "https://ezhire.life/erp/media/2024/10/28/8f76246d-858.png",
            "daily_rate": 390.6,
            "weekly_rate": 390.4,
            "monthly_rate": 223.9,
            "tax_rate": 5,
            "currency": "AED",
            "total_estimated_amount_weekly": 409.92,
            "total_estimated_amount_daily": 410.13,
            "total_estimated_amount_monthly": 235.1,
            "daily_allowed_km": 300.0,
            "weekly_allowed_km": 250.0,
            "monthly_allowed_km": 133.33,
            "extra_km_price": 1.0,
            "transmission": "AT",
            "number_of_seats": 7,
            "air_conditioning": 1,
            "number_of_doors": 5,
            "luggage_capacity": 4,
            "car_name": "Toyota Fortuner & Similar (CRX)"
        }
    ]
}
;

const { data } = vehicles;

console.log("LIST OF VEHICLES")
for (let i = 0; i < data.length; i++) {
    console.log(data[i].model);
};