SELECT 
    COALESCE(booking_year, 'Total') AS booking_year,
    COALESCE(booking_month, 'Total') AS booking_month,
    COALESCE(booking_day_of_month, 'Total') AS booking_day_of_month,
    FORMAT(COUNT(CASE WHEN pickup_day_of_month = '01' THEN 1 END), 0) AS '01',
    FORMAT(COUNT(CASE WHEN pickup_day_of_month = '02' THEN 1 END), 0) AS '02',
    FORMAT(COUNT(CASE WHEN pickup_day_of_month = '03' THEN 1 END), 0) AS '03',
    FORMAT(COUNT(CASE WHEN pickup_day_of_month = '04' THEN 1 END), 0) AS '04',
    FORMAT(COUNT(CASE WHEN pickup_day_of_month = '05' THEN 1 END), 0) AS '05',
    FORMAT(COUNT(CASE WHEN pickup_day_of_month = '06' THEN 1 END), 0) AS '06',
    FORMAT(COUNT(CASE WHEN pickup_day_of_month = '07' THEN 1 END), 0) AS '07',
    FORMAT(COUNT(CASE WHEN pickup_day_of_month = '08' THEN 1 END), 0) AS '08',
    FORMAT(COUNT(CASE WHEN pickup_day_of_month = '09' THEN 1 END), 0) AS '09',
    FORMAT(COUNT(CASE WHEN pickup_day_of_month = '10' THEN 1 END), 0) AS '10',
    FORMAT(COUNT(CASE WHEN pickup_day_of_month = '11' THEN 1 END), 0) AS '11',
    FORMAT(COUNT(CASE WHEN pickup_day_of_month = '12' THEN 1 END), 0) AS '12',
    FORMAT(COUNT(CASE WHEN pickup_day_of_month = '13' THEN 1 END), 0) AS '13',
    FORMAT(COUNT(CASE WHEN pickup_day_of_month = '14' THEN 1 END), 0) AS '14',
    FORMAT(COUNT(CASE WHEN pickup_day_of_month = '15' THEN 1 END), 0) AS '15',
    FORMAT(COUNT(CASE WHEN pickup_day_of_month = '16' THEN 1 END), 0) AS '16',
    FORMAT(COUNT(CASE WHEN pickup_day_of_month = '17' THEN 1 END), 0) AS '17',
    FORMAT(COUNT(CASE WHEN pickup_day_of_month = '18' THEN 1 END), 0) AS '18',
    FORMAT(COUNT(CASE WHEN pickup_day_of_month = '19' THEN 1 END), 0) AS '19',
    FORMAT(COUNT(CASE WHEN pickup_day_of_month = '20' THEN 1 END), 0) AS '20',
    FORMAT(COUNT(CASE WHEN pickup_day_of_month = '21' THEN 1 END), 0) AS '21',
    FORMAT(COUNT(CASE WHEN pickup_day_of_month = '22' THEN 1 END), 0) AS '22',
    FORMAT(COUNT(CASE WHEN pickup_day_of_month = '23' THEN 1 END), 0) AS '23',
    FORMAT(COUNT(CASE WHEN pickup_day_of_month = '24' THEN 1 END), 0) AS '24',
    FORMAT(COUNT(CASE WHEN pickup_day_of_month = '25' THEN 1 END), 0) AS '25',
    FORMAT(COUNT(CASE WHEN pickup_day_of_month = '26' THEN 1 END), 0) AS '26',
    FORMAT(COUNT(CASE WHEN pickup_day_of_month = '27' THEN 1 END), 0) AS '27',
    FORMAT(COUNT(CASE WHEN pickup_day_of_month = '28' THEN 1 END), 0) AS '28',
    FORMAT(COUNT(CASE WHEN pickup_day_of_month = '29' THEN 1 END), 0) AS '29',
    FORMAT(COUNT(CASE WHEN pickup_day_of_month = '30' THEN 1 END), 0) AS '30',
    FORMAT(COUNT(CASE WHEN pickup_day_of_month = '31' THEN 1 END), 0) AS '31',
    FORMAT(COUNT(booking_datetime), 0) AS Total,
    FORMAT(COUNT(booking_datetime) - COUNT(CASE WHEN status = 'Cancelled by User' THEN 1 END), 0) AS 'T xCancel'
FROM ezhire_booking_data.booking_data
WHERE status <> "Cancelled by User"
GROUP BY booking_year, booking_month, booking_day_of_month WITH ROLLUP
ORDER BY booking_year DESC, booking_month DESC, booking_day_of_month DESC;